### ISSUE TITLE
Optimize load time

### ISSUE THREAD

**Issue by shubhamcodez** [shubhamcodez/XMeme#5]
Load time has become slow because of so many memes. Any suggestions to optimization is welcome.

**Comment by Godwindaniel10** [comment]
hi. I'm Danny, can I address this issue?

**Comment by shubhamcodez** [comment]
> hi. I'm Danny, can I address this issue?

Sure, Danny. Any help is welcome.

**Comment by Godwindaniel10** [comment]
ok, I got this.

**Comment by Godwindaniel10** [comment]
Hi😊 @shubhamcodez , How do I get my hands on the images?     I guess you are using an API

**Comment by shubhamcodez** [comment]
Umm, You could just upload them via link. 

> Hi😊 @shubhamcodez , How do I get my hands on the images? I guess you are using an API

Do you mean meme images? If yes, You could upload them using a link and it fetches and displays them from the link. 
Let me know if you want more information.

**Comment by Godwindaniel10** [comment]
ok

**Comment by Godwindaniel10** [comment]
Hi @shubhamcodez , the memes images are responsible for page slow load time, and I don't really know how I can fix that if it's fetching memes images. but the images are 90% responsible.   

You can look up your website performance using https://web.dev/

And you can reach me if you got an idea on how to fix it.

![xmeme1](https://user-images.githubusercontent.com/54848535/111871832-06573900-8984-11eb-8ffa-9d606ee15391.JPG)

**Comment by shubhamcodez** [comment]
> Hi @shubhamcodez , the memes images are responsible for page slow load time, and I don't really know how I can fix that if it's fetching memes images. but the images are 90% responsible.
> 
> You can look up your website performance using https://web.dev/
> 
> And you can reach me if you got an idea on how to fix it.
> 
> ![xmeme1](https://user-images.githubusercontent.com/54848535/111871832-06573900-8984-11eb-8ffa-9d606ee15391.JPG)

Hey, I think one of the reasons for the slow load time is because of sorting that happens everytime the page is loaded. Right? I think, We could work around that. Tell me what do you think?

**Comment by Godwindaniel10** [comment]
That's a brilliant idea. 
What's the plan?

**Comment by Godwindaniel10** [comment]
And some memes images arent showing, I guess the problem is due to the user pasting an unrecognized URL.

I did that mistake as well on the first try.

I think you should add an example of what the ( URL ) most look like in order for the meme image to be displayed.

what do you think?

**Comment by shubhamcodez** [comment]
> That's a brilliant idea.
> What's the plan?
We could just display from the last, not sure if it'll decrease the load time. We could try that.

You could try making changes in client.js
You'll find a for loop at line 60.
remove memes.reverse() and change 
for loop to, 
for(var i = len; i >= len-100; i--)

**Comment by shubhamcodez** [comment]
> And some memes images arent showing, I guess the problem is due to the user pasting an unrecognized URL.
> 
> I did that mistake as well on the first try.
> 
> I think you should add an example of what the ( URL ) most look like in order for the meme image to be displayed.
> 
> what do you think?

Good suggestion.
I have thought on that. I made an edit (patch) method to solve that but it isn't working, could you care to look at that if you know how to work around it.

**Comment by shubhamcodez** [comment]
@Godwindaniel10 Feel free to add new issues as you see them. Appreciate the effort. 😄

**Comment by Godwindaniel10** [comment]
@shubhamcodez I am so grateful.

i have changed the code on line ( 60 ) to this                for (var i = len; i >= len-100; i--) .

but I want to run the backend and frontend page on localhost, to see how the changes work, but unfortunately, the backend is not working

**Comment by shubhamcodez** [comment]
> @shubhamcodez I am so grateful.
> 
> i have changed the code on line ( 60 ) to this for (var i = len; i >= len-100; i--) .
> 
> but I want to run the backend and frontend page on localhost, to see how the changes work, but unfortunately, the backend is not working

What wrong? Did you follow the instructions provided in the ReadMe?

**Comment by Godwindaniel10** [comment]
yeah!

**Comment by shubhamcodez** [comment]
> yeah!

What's the issue you're getting?

**Comment by Godwindaniel10** [comment]
![nodemon issue](https://user-images.githubusercontent.com/54848535/111877994-e765a080-899d-11eb-84e2-4897be668dc2.JPG)

**Comment by shubhamcodez** [comment]
cd to Backend folder and then try running

**Comment by shubhamcodez** [comment]
Just put a PR if it's not working.
I'll make sure it runs on my system and merge it, if it's good to go.

**Comment by Godwindaniel10** [comment]
still got another error, i think i will put  PR
